
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.233.64.0/18

# Example configuration.yaml entry
device_tracker:
  - platform: ddwrt
    host: 172.16.1.4
    username: !secret ap_username
    password: !secret ap_password
    ssl: true
    verify_ssl: false

sensor:
  - platform: ups
    username: !secret ups_username
    password: !secret ups_password